// Externals
const fs = require('fs')
const path = require('path')

// Mock base64 attachments array (with truncated content)
const attachments = [
  {
    name: 'enriched_sales_data.csv',
    type: 'application/octet-stream',
    size: 652,
    content: 'SUQsRGF0ZSxRdWFydGVyLFJlZ2lvbixNYW5hZ2VyLFNhbGVzICgkKSxQcm9kdWN0cyBTb2xkLFRvcCBQcm9kdWN0LE5ldyBDdXN0b21lcnMsUmVwZWF0IEN1c3RvbWVycwpTMDAxLDIwMjUtMDEtMDUsUTEsTm9ydGgsQWxpY2UgSmVubmluZ3MsNjUwMDAsMjQ1LEFuYWx5dGljcyBQcm8sMzQsODkKUzAwMiwyMDI1LTAxLTEyLFExLFNvdXRoLE1hcmNvIEFsdmFyZXosODQwMDAsMzEyLERhdGEgV3JhbmdsZXIsNTgsMTEwClMwMDMsMjAyNS0wMS0xOSxRMSxFYXN0LEdyYWNlIExlZSw1NjAwMCwxOTgsSW5zaWdodCBUcmFja2VyLDIyLDc2ClMwMDQsMjAyNS0wMS0yNixRMSxXZXN0LEpvcmRhbiBSaXZlcmEsMTE5NTI4LDUyOSxSZXBvcnQgQnVpbGRlciw4MSwxNDUKUzAwNSwyMDI1LTAyLTAyLFExLE5vcnRoLEFsaWNlIEplbm5pbmdzLDYxMzAwLDIzMSxBbmFseXRpY3MgUHJvLDMxLDkzClMwMDYsMjAyNS0wMi0wOSxRMSxTb3V0aCxNYXJjbyBBbHZhcmV6LDgyMTAwLDMwNyxEYXRhIFdyYW5nbGVyLDUwLDExNgpTMDA3LDIwMjUtMDItMTYsUTEsRWFzdCxHcmFjZSBMZWUsNTk0NTAsMjE1LEluc2lnaHQgVHJhY2tlciwyNCw3OQpTMDA4LDIwMjUtMDItMjMsUTEsV2VzdCxKb3JkYW4gUml2ZXJhLDEyMjY0MCw1MzgsUmVwb3J0IEJ1aWxkZXIsODksMTUxCg==',
    contentId: ''
  },
  {
    name: 'employee_performance_data.json',
    type: 'application/octet-stream',
    size: 1976,
    content: 'WwogIHsKICAgICJlbXBsb3llZUlkIjogIkUxMDEiLAogICAgIm5hbWUiOiAiQWxpY2UgSmVubmluZ3MiLAogICAgImRlcGFydG1lbnQiOiAiU2FsZXMiLAogICAgInBvc2l0aW9uIjogIlJlZ2lvbmFsIE1hbmFnZXIiLAogICAgInJldmlld0RhdGUiOiAiMjAyNS0wMy0wMSIsCiAgICAicmV2aWV3ZXIiOiAiRGVyZWsgTWFzb24iLAogICAgInNjb3JlcyI6IHsKICAgICAgImNvbW11bmljYXRpb24iOiA0LjcsCiAgICAgICJsZWFkZXJzaGlwIjogNC41LAogICAgICAiaW5pdGlhdGl2ZSI6IDQuOCwKICAgICAgImNvbGxhYm9yYXRpb24iOiA0LjYsCiAgICAgICJ0ZWNobmljYWxTa2lsbCI6IDQuMQogICAgfSwKICAgICJvdmVyYWxsUmF0aW5nIjogNC41LAogICAgImZlZWRiYWNrIjogIkNvbnNpc3RlbnRseSBleGNlZWRzIGV4cGVjdGF0aW9ucyBpbiB0ZWFtIGxlYWRlcnNoaXAgYW5kIGNyb3NzLWRlcGFydG1lbnRhbCBjb21tdW5pY2F0aW9uLiIKICB9LAogIHsKICAgICJlbXBsb3llZUlkIjogIkUxMDIiLAogICAgIm5hbWUiOiAiTWFyY28gQWx2YXJleiIsCiAgICAiZGVwYXJ0bWVudCI6ICJDdXN0b21lciBTdWNjZXNzIiwKICAgICJwb3NpdGlvbiI6ICJBY2NvdW50IEV4ZWN1dGl2ZSIsCiAgICAicmV2aWV3RGF0ZSI6ICIyMDI1LTAzLTAxIiwKICAgICJyZXZpZXdlciI6ICJOaW5hIFpob3UiLAogICAgInNjb3JlcyI6IHsKICAgICAgImNvbW11bmljYXRpb24iOiA0LjIsCiAgICAgICJsZWFkZXJzaGlwIjogMy45LAogICAgICAiaW5pdGlhdGl2ZSI6IDQuNCwKICAgICAgImNvbGxhYm9yYXRpb24iOiA0LjcsCiAgICAgICJ0ZWNobmljYWxTa2lsbCI6IDMuOAogICAgfSwKICAgICJvdmVyYWxsUmF0aW5nIjogNC4yLAogICAgImZlZWRiYWNrIjogIlN0cm9uZyBjb2xsYWJvcmF0aW9uIHNraWxscyBhbmQgcHJvYWN0aXZlIGNsaWVudCBlbmdhZ2VtZW50LiBTb21lIHJvb20gZm9yIGdyb3d0aCBpbiB0ZWNobmljYWwgYXJlYXMuIgogIH0sCiAgewogICAgImVtcGxveWVlSWQiOiAiRTEwMyIsCiAgICAibmFtZSI6ICJHcmFjZSBMZWUiLAogICAgImRlcGFydG1lbnQiOiAiRW5naW5lZXJpbmciLAogICAgInBvc2l0aW9uIjogIlNvZnR3YXJlIEVuZ2luZWVyIiwKICAgICJyZXZpZXdEYXRlIjogIjIwMjUtMDMtMDEiLAogICAgInJldmlld2VyIjogIlRob21hcyBHcmVlbiIsCiAgICAic2NvcmVzIjogewogICAgICAiY29tbXVuaWNhdGlvbiI6IDQuMSwKICAgICAgImxlYWRlcnNoaXAiOiA0LjAsCiAgICAgICJpbml0aWF0aXZlIjogNC42LAogICAgICAiY29sbGFib3JhdGlvbiI6IDQuMywKICAgICAgInRlY2huaWNhbFNraWxsIjogNC45CiAgICB9LAogICAgIm92ZXJhbGxSYXRpbmciOiA0LjYsCiAgICAiZmVlZGJhY2siOiAiSGlnaGx5IHNraWxsZWQgdGVjaG5pY2FsbHkgYW5kIHRha2VzIGluaXRpYXRpdmUgaW4gc3ByaW50IHBsYW5uaW5nLiBFbWVyZ2luZyBsZWFkZXJzaGlwIHF1YWxpdGllcy4iCiAgfSwKICB7CiAgICAiZW1wbG95ZWVJZCI6ICJFMTA0IiwKICAgICJuYW1lIjogIkpvcmRhbiBSaXZlcmEiLAogICAgImRlcGFydG1lbnQiOiAiUHJvZHVjdCIsCiAgICAicG9zaXRpb24iOiAiUHJvZHVjdCBNYW5hZ2VyIiwKICAgICJyZXZpZXdEYXRlIjogIjIwMjUtMDMtMDEiLAogICAgInJldmlld2VyIjogIkxlbmEgV3JpZ2h0IiwKICAgICJzY29yZXMiOiB7CiAgICAgICJjb21tdW5pY2F0aW9uIjogNC44LAogICAgICAibGVhZGVyc2hpcCI6IDQuOSwKICAgICAgImluaXRpYXRpdmUiOiA0LjYsCiAgICAgICJjb2xsYWJvcmF0aW9uIjogNC45LAogICAgICAidGVjaG5pY2FsU2tpbGwiOiA0LjAKICAgIH0sCiAgICAib3ZlcmFsbFJhdGluZyI6IDQuNywKICAgICJmZWVkYmFjayI6ICJTdHJvbmcgbGVhZGVyc2hpcCBhbmQgZXhjZWxsZW50IGF0IGNyb3NzLXRlYW0gY29tbXVuaWNhdGlvbi4gVmFsdWFibGUgYXNzZXQgdG8gdGhlIHByb2R1Y3QgbGlmZWN5Y2xlLiIKICB9Cl0=',
    contentId: ''
  }
]

// Directory to save files
const outputDir = './recovered_files'

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir)
}

attachments.forEach(attachment => {
  try {
    const buffer = Buffer.from(attachment.content, 'base64')
    const filePath = path.join(outputDir, attachment.name)

    fs.writeFileSync(filePath, buffer)
    console.log(`✅ Saved file: ${filePath}`)
  } catch (error) {
    console.error(`❌ Failed to save ${attachment.name}:`, error)
  }
})